//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrnFacturaElectronica.wsdl_dfacture {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaGeneral", Namespace="http://schemas.datacontract.org/2004/07/Services.Models.Object")]
    [System.SerializableAttribute()]
    public partial class FacturaGeneral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrnFacturaElectronica.wsdl_dfacture.Cliente clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string consecutivoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string consecutivoDocumentoModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrnFacturaElectronica.wsdl_dfacture.FacturaDetalle[] detalleDeFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrnFacturaElectronica.wsdl_dfacture.Extras[] extrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaEmisionDocumentoModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icotermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string importeTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrnFacturaElectronica.wsdl_dfacture.FacturaImpuestos[] impuestosGeneralesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string informacionAdicionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string medioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string motivoNotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string propinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rangoNumeracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string totalDescuentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string totalSinImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uuidDocumentoModificadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrnFacturaElectronica.wsdl_dfacture.Cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.clienteField, value) != true)) {
                    this.clienteField = value;
                    this.RaisePropertyChanged("cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string consecutivoDocumento {
            get {
                return this.consecutivoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.consecutivoDocumentoField, value) != true)) {
                    this.consecutivoDocumentoField = value;
                    this.RaisePropertyChanged("consecutivoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string consecutivoDocumentoModificado {
            get {
                return this.consecutivoDocumentoModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.consecutivoDocumentoModificadoField, value) != true)) {
                    this.consecutivoDocumentoModificadoField = value;
                    this.RaisePropertyChanged("consecutivoDocumentoModificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrnFacturaElectronica.wsdl_dfacture.FacturaDetalle[] detalleDeFactura {
            get {
                return this.detalleDeFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleDeFacturaField, value) != true)) {
                    this.detalleDeFacturaField = value;
                    this.RaisePropertyChanged("detalleDeFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoPago {
            get {
                return this.estadoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoPagoField, value) != true)) {
                    this.estadoPagoField = value;
                    this.RaisePropertyChanged("estadoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrnFacturaElectronica.wsdl_dfacture.Extras[] extras {
            get {
                return this.extrasField;
            }
            set {
                if ((object.ReferenceEquals(this.extrasField, value) != true)) {
                    this.extrasField = value;
                    this.RaisePropertyChanged("extras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaEmisionField, value) != true)) {
                    this.fechaEmisionField = value;
                    this.RaisePropertyChanged("fechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaEmisionDocumentoModificado {
            get {
                return this.fechaEmisionDocumentoModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaEmisionDocumentoModificadoField, value) != true)) {
                    this.fechaEmisionDocumentoModificadoField = value;
                    this.RaisePropertyChanged("fechaEmisionDocumentoModificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaVencimientoField, value) != true)) {
                    this.fechaVencimientoField = value;
                    this.RaisePropertyChanged("fechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string icoterms {
            get {
                return this.icotermsField;
            }
            set {
                if ((object.ReferenceEquals(this.icotermsField, value) != true)) {
                    this.icotermsField = value;
                    this.RaisePropertyChanged("icoterms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string importeTotal {
            get {
                return this.importeTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.importeTotalField, value) != true)) {
                    this.importeTotalField = value;
                    this.RaisePropertyChanged("importeTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrnFacturaElectronica.wsdl_dfacture.FacturaImpuestos[] impuestosGenerales {
            get {
                return this.impuestosGeneralesField;
            }
            set {
                if ((object.ReferenceEquals(this.impuestosGeneralesField, value) != true)) {
                    this.impuestosGeneralesField = value;
                    this.RaisePropertyChanged("impuestosGenerales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string informacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                if ((object.ReferenceEquals(this.informacionAdicionalField, value) != true)) {
                    this.informacionAdicionalField = value;
                    this.RaisePropertyChanged("informacionAdicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string medioPago {
            get {
                return this.medioPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.medioPagoField, value) != true)) {
                    this.medioPagoField = value;
                    this.RaisePropertyChanged("medioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((object.ReferenceEquals(this.monedaField, value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motivoNota {
            get {
                return this.motivoNotaField;
            }
            set {
                if ((object.ReferenceEquals(this.motivoNotaField, value) != true)) {
                    this.motivoNotaField = value;
                    this.RaisePropertyChanged("motivoNota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string propina {
            get {
                return this.propinaField;
            }
            set {
                if ((object.ReferenceEquals(this.propinaField, value) != true)) {
                    this.propinaField = value;
                    this.RaisePropertyChanged("propina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rangoNumeracion {
            get {
                return this.rangoNumeracionField;
            }
            set {
                if ((object.ReferenceEquals(this.rangoNumeracionField, value) != true)) {
                    this.rangoNumeracionField = value;
                    this.RaisePropertyChanged("rangoNumeracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDocumentoField, value) != true)) {
                    this.tipoDocumentoField = value;
                    this.RaisePropertyChanged("tipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalDescuentos {
            get {
                return this.totalDescuentosField;
            }
            set {
                if ((object.ReferenceEquals(this.totalDescuentosField, value) != true)) {
                    this.totalDescuentosField = value;
                    this.RaisePropertyChanged("totalDescuentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalSinImpuestos {
            get {
                return this.totalSinImpuestosField;
            }
            set {
                if ((object.ReferenceEquals(this.totalSinImpuestosField, value) != true)) {
                    this.totalSinImpuestosField = value;
                    this.RaisePropertyChanged("totalSinImpuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uuidDocumentoModificado {
            get {
                return this.uuidDocumentoModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.uuidDocumentoModificadoField, value) != true)) {
                    this.uuidDocumentoModificadoField = value;
                    this.RaisePropertyChanged("uuidDocumentoModificado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Services.Models.Object")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreRazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notificarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regimenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoPersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                if ((object.ReferenceEquals(this.ciudadField, value) != true)) {
                    this.ciudadField = value;
                    this.RaisePropertyChanged("ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreRazonSocial {
            get {
                return this.nombreRazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreRazonSocialField, value) != true)) {
                    this.nombreRazonSocialField = value;
                    this.RaisePropertyChanged("nombreRazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notificar {
            get {
                return this.notificarField;
            }
            set {
                if ((object.ReferenceEquals(this.notificarField, value) != true)) {
                    this.notificarField = value;
                    this.RaisePropertyChanged("notificar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDocumentoField, value) != true)) {
                    this.numeroDocumentoField = value;
                    this.RaisePropertyChanged("numeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                if ((object.ReferenceEquals(this.paisField, value) != true)) {
                    this.paisField = value;
                    this.RaisePropertyChanged("pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referencia2 {
            get {
                return this.referencia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.referencia2Field, value) != true)) {
                    this.referencia2Field = value;
                    this.RaisePropertyChanged("referencia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string regimen {
            get {
                return this.regimenField;
            }
            set {
                if ((object.ReferenceEquals(this.regimenField, value) != true)) {
                    this.regimenField = value;
                    this.RaisePropertyChanged("regimen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoNombreField, value) != true)) {
                    this.segundoNombreField = value;
                    this.RaisePropertyChanged("segundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subDivision {
            get {
                return this.subDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.subDivisionField, value) != true)) {
                    this.subDivisionField = value;
                    this.RaisePropertyChanged("subDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoIdentificacionField, value) != true)) {
                    this.tipoIdentificacionField = value;
                    this.RaisePropertyChanged("tipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoPersonaField, value) != true)) {
                    this.tipoPersonaField = value;
                    this.RaisePropertyChanged("tipoPersona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDetalle", Namespace="http://schemas.datacontract.org/2004/07/Services.Models.Object")]
    [System.SerializableAttribute()]
    public partial class FacturaDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cantidadUnidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalleAdicionalNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalleAdicionalValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrnFacturaElectronica.wsdl_dfacture.FacturaImpuestos[] impuestosDetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precioTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precioTotalSinImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precioVentaUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cantidadUnidades {
            get {
                return this.cantidadUnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.cantidadUnidadesField, value) != true)) {
                    this.cantidadUnidadesField = value;
                    this.RaisePropertyChanged("cantidadUnidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoProductoField, value) != true)) {
                    this.codigoProductoField = value;
                    this.RaisePropertyChanged("codigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descuento {
            get {
                return this.descuentoField;
            }
            set {
                if ((object.ReferenceEquals(this.descuentoField, value) != true)) {
                    this.descuentoField = value;
                    this.RaisePropertyChanged("descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalleAdicionalNombre {
            get {
                return this.detalleAdicionalNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleAdicionalNombreField, value) != true)) {
                    this.detalleAdicionalNombreField = value;
                    this.RaisePropertyChanged("detalleAdicionalNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalleAdicionalValor {
            get {
                return this.detalleAdicionalValorField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleAdicionalValorField, value) != true)) {
                    this.detalleAdicionalValorField = value;
                    this.RaisePropertyChanged("detalleAdicionalValor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrnFacturaElectronica.wsdl_dfacture.FacturaImpuestos[] impuestosDetalles {
            get {
                return this.impuestosDetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.impuestosDetallesField, value) != true)) {
                    this.impuestosDetallesField = value;
                    this.RaisePropertyChanged("impuestosDetalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string precioTotal {
            get {
                return this.precioTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.precioTotalField, value) != true)) {
                    this.precioTotalField = value;
                    this.RaisePropertyChanged("precioTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string precioTotalSinImpuestos {
            get {
                return this.precioTotalSinImpuestosField;
            }
            set {
                if ((object.ReferenceEquals(this.precioTotalSinImpuestosField, value) != true)) {
                    this.precioTotalSinImpuestosField = value;
                    this.RaisePropertyChanged("precioTotalSinImpuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string precioVentaUnitario {
            get {
                return this.precioVentaUnitarioField;
            }
            set {
                if ((object.ReferenceEquals(this.precioVentaUnitarioField, value) != true)) {
                    this.precioVentaUnitarioField = value;
                    this.RaisePropertyChanged("precioVentaUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seriales {
            get {
                return this.serialesField;
            }
            set {
                if ((object.ReferenceEquals(this.serialesField, value) != true)) {
                    this.serialesField = value;
                    this.RaisePropertyChanged("seriales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.unidadMedidaField, value) != true)) {
                    this.unidadMedidaField = value;
                    this.RaisePropertyChanged("unidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Extras", Namespace="http://schemas.datacontract.org/2004/07/Services.Models.Object")]
    [System.SerializableAttribute()]
    public partial class Extras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string controlInterno1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string controlInterno2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string controlInterno1 {
            get {
                return this.controlInterno1Field;
            }
            set {
                if ((object.ReferenceEquals(this.controlInterno1Field, value) != true)) {
                    this.controlInterno1Field = value;
                    this.RaisePropertyChanged("controlInterno1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string controlInterno2 {
            get {
                return this.controlInterno2Field;
            }
            set {
                if ((object.ReferenceEquals(this.controlInterno2Field, value) != true)) {
                    this.controlInterno2Field = value;
                    this.RaisePropertyChanged("controlInterno2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pdf {
            get {
                return this.pdfField;
            }
            set {
                if ((object.ReferenceEquals(this.pdfField, value) != true)) {
                    this.pdfField = value;
                    this.RaisePropertyChanged("pdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlField, value) != true)) {
                    this.xmlField = value;
                    this.RaisePropertyChanged("xml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaImpuestos", Namespace="http://schemas.datacontract.org/2004/07/Services.Models.Object")]
    [System.SerializableAttribute()]
    public partial class FacturaImpuestos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baseImponibleTOTALImpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoTOTALImpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string controlInternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porcentajeTOTALImpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorTOTALImpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baseImponibleTOTALImp {
            get {
                return this.baseImponibleTOTALImpField;
            }
            set {
                if ((object.ReferenceEquals(this.baseImponibleTOTALImpField, value) != true)) {
                    this.baseImponibleTOTALImpField = value;
                    this.RaisePropertyChanged("baseImponibleTOTALImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoTOTALImp {
            get {
                return this.codigoTOTALImpField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoTOTALImpField, value) != true)) {
                    this.codigoTOTALImpField = value;
                    this.RaisePropertyChanged("codigoTOTALImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string controlInterno {
            get {
                return this.controlInternoField;
            }
            set {
                if ((object.ReferenceEquals(this.controlInternoField, value) != true)) {
                    this.controlInternoField = value;
                    this.RaisePropertyChanged("controlInterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string porcentajeTOTALImp {
            get {
                return this.porcentajeTOTALImpField;
            }
            set {
                if ((object.ReferenceEquals(this.porcentajeTOTALImpField, value) != true)) {
                    this.porcentajeTOTALImpField = value;
                    this.RaisePropertyChanged("porcentajeTOTALImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valorTOTALImp {
            get {
                return this.valorTOTALImpField;
            }
            set {
                if ((object.ReferenceEquals(this.valorTOTALImpField, value) != true)) {
                    this.valorTOTALImpField = value;
                    this.RaisePropertyChanged("valorTOTALImp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.Response")]
    [System.SerializableAttribute()]
    public partial class DocumentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string consecutivoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string consecutivoDocumento {
            get {
                return this.consecutivoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.consecutivoDocumentoField, value) != true)) {
                    this.consecutivoDocumentoField = value;
                    this.RaisePropertyChanged("consecutivoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cufe {
            get {
                return this.cufeField;
            }
            set {
                if ((object.ReferenceEquals(this.cufeField, value) != true)) {
                    this.cufeField = value;
                    this.RaisePropertyChanged("cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaRespuestaField, value) != true)) {
                    this.fechaRespuestaField = value;
                    this.RaisePropertyChanged("fechaRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlField, value) != true)) {
                    this.xmlField = value;
                    this.RaisePropertyChanged("xml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.Response")]
    [System.SerializableAttribute()]
    public partial class DocumentStatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string acuseComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string acuseEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string acuseResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string acuseRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatusDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acuseComentario {
            get {
                return this.acuseComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.acuseComentarioField, value) != true)) {
                    this.acuseComentarioField = value;
                    this.RaisePropertyChanged("acuseComentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acuseEstatus {
            get {
                return this.acuseEstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.acuseEstatusField, value) != true)) {
                    this.acuseEstatusField = value;
                    this.RaisePropertyChanged("acuseEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acuseResponsable {
            get {
                return this.acuseResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.acuseResponsableField, value) != true)) {
                    this.acuseResponsableField = value;
                    this.RaisePropertyChanged("acuseResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acuseRespuesta {
            get {
                return this.acuseRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.acuseRespuestaField, value) != true)) {
                    this.acuseRespuestaField = value;
                    this.RaisePropertyChanged("acuseRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cufe {
            get {
                return this.cufeField;
            }
            set {
                if ((object.ReferenceEquals(this.cufeField, value) != true)) {
                    this.cufeField = value;
                    this.RaisePropertyChanged("cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatusDocumento {
            get {
                return this.estatusDocumentoField;
            }
            set {
                if ((this.estatusDocumentoField.Equals(value) != true)) {
                    this.estatusDocumentoField = value;
                    this.RaisePropertyChanged("estatusDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaDocumento {
            get {
                return this.fechaDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaDocumentoField, value) != true)) {
                    this.fechaDocumentoField = value;
                    this.RaisePropertyChanged("fechaDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensajeDocumento {
            get {
                return this.mensajeDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeDocumentoField, value) != true)) {
                    this.mensajeDocumentoField = value;
                    this.RaisePropertyChanged("mensajeDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.Response")]
    [System.SerializableAttribute()]
    public partial class SendEmailResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadPDFResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.Response")]
    [System.SerializableAttribute()]
    public partial class DownloadPDFResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cufe {
            get {
                return this.cufeField;
            }
            set {
                if ((object.ReferenceEquals(this.cufeField, value) != true)) {
                    this.cufeField = value;
                    this.RaisePropertyChanged("cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadXMLResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.Response")]
    [System.SerializableAttribute()]
    public partial class DownloadXMLResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cufe {
            get {
                return this.cufeField;
            }
            set {
                if ((object.ReferenceEquals(this.cufeField, value) != true)) {
                    this.cufeField = value;
                    this.RaisePropertyChanged("cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoliosRemainingResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.Response")]
    [System.SerializableAttribute()]
    public partial class FoliosRemainingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int foliosRestantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int foliosRestantes {
            get {
                return this.foliosRestantesField;
            }
            set {
                if ((this.foliosRestantesField.Equals(value) != true)) {
                    this.foliosRestantesField = value;
                    this.RaisePropertyChanged("foliosRestantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadCertificateResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.Response")]
    [System.SerializableAttribute()]
    public partial class LoadCertificateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateXML", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    [System.SerializableAttribute()]
    public partial class ValidateXML : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsdl_dfacture.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Enviar", ReplyAction="http://tempuri.org/IService/EnviarResponse")]
        TrnFacturaElectronica.wsdl_dfacture.DocumentResponse Enviar(string tokenEmpresa, string tokenPassword, TrnFacturaElectronica.wsdl_dfacture.FacturaGeneral factura, string adjuntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Enviar", ReplyAction="http://tempuri.org/IService/EnviarResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DocumentResponse> EnviarAsync(string tokenEmpresa, string tokenPassword, TrnFacturaElectronica.wsdl_dfacture.FacturaGeneral factura, string adjuntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EstadoDocumento", ReplyAction="http://tempuri.org/IService/EstadoDocumentoResponse")]
        TrnFacturaElectronica.wsdl_dfacture.DocumentStatusResponse EstadoDocumento(string tokenEmpresa, string tokenPassword, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EstadoDocumento", ReplyAction="http://tempuri.org/IService/EstadoDocumentoResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DocumentStatusResponse> EstadoDocumentoAsync(string tokenEmpresa, string tokenPassword, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EnvioCorreo", ReplyAction="http://tempuri.org/IService/EnvioCorreoResponse")]
        TrnFacturaElectronica.wsdl_dfacture.SendEmailResponse EnvioCorreo(string tokenEmpresa, string tokenPassword, string documento, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EnvioCorreo", ReplyAction="http://tempuri.org/IService/EnvioCorreoResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.SendEmailResponse> EnvioCorreoAsync(string tokenEmpresa, string tokenPassword, string documento, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DescargaPDF", ReplyAction="http://tempuri.org/IService/DescargaPDFResponse")]
        TrnFacturaElectronica.wsdl_dfacture.DownloadPDFResponse DescargaPDF(string tokenEmpresa, string tokenPassword, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DescargaPDF", ReplyAction="http://tempuri.org/IService/DescargaPDFResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DownloadPDFResponse> DescargaPDFAsync(string tokenEmpresa, string tokenPassword, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DescargaXML", ReplyAction="http://tempuri.org/IService/DescargaXMLResponse")]
        TrnFacturaElectronica.wsdl_dfacture.DownloadXMLResponse DescargaXML(string tokenEmpresa, string tokenPassword, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DescargaXML", ReplyAction="http://tempuri.org/IService/DescargaXMLResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DownloadXMLResponse> DescargaXMLAsync(string tokenEmpresa, string tokenPassword, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FoliosRestantes", ReplyAction="http://tempuri.org/IService/FoliosRestantesResponse")]
        TrnFacturaElectronica.wsdl_dfacture.FoliosRemainingResponse FoliosRestantes(string tokenEmpresa, string tokenPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FoliosRestantes", ReplyAction="http://tempuri.org/IService/FoliosRestantesResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.FoliosRemainingResponse> FoliosRestantesAsync(string tokenEmpresa, string tokenPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CargarCertificado", ReplyAction="http://tempuri.org/IService/CargarCertificadoResponse")]
        TrnFacturaElectronica.wsdl_dfacture.LoadCertificateResponse CargarCertificado(string tokenEmpresa, string tokenPassword, string certificado, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CargarCertificado", ReplyAction="http://tempuri.org/IService/CargarCertificadoResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.LoadCertificateResponse> CargarCertificadoAsync(string tokenEmpresa, string tokenPassword, string certificado, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarXml", ReplyAction="http://tempuri.org/IService/ValidarXmlResponse")]
        TrnFacturaElectronica.wsdl_dfacture.ValidateXML ValidarXml(string tokenEmpresa, string tokenPassword, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarXml", ReplyAction="http://tempuri.org/IService/ValidarXmlResponse")]
        System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.ValidateXML> ValidarXmlAsync(string tokenEmpresa, string tokenPassword, string documento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TrnFacturaElectronica.wsdl_dfacture.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TrnFacturaElectronica.wsdl_dfacture.IService>, TrnFacturaElectronica.wsdl_dfacture.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.DocumentResponse Enviar(string tokenEmpresa, string tokenPassword, TrnFacturaElectronica.wsdl_dfacture.FacturaGeneral factura, string adjuntos) {
            return base.Channel.Enviar(tokenEmpresa, tokenPassword, factura, adjuntos);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DocumentResponse> EnviarAsync(string tokenEmpresa, string tokenPassword, TrnFacturaElectronica.wsdl_dfacture.FacturaGeneral factura, string adjuntos) {
            return base.Channel.EnviarAsync(tokenEmpresa, tokenPassword, factura, adjuntos);
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.DocumentStatusResponse EstadoDocumento(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.EstadoDocumento(tokenEmpresa, tokenPassword, documento);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DocumentStatusResponse> EstadoDocumentoAsync(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.EstadoDocumentoAsync(tokenEmpresa, tokenPassword, documento);
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.SendEmailResponse EnvioCorreo(string tokenEmpresa, string tokenPassword, string documento, string correo) {
            return base.Channel.EnvioCorreo(tokenEmpresa, tokenPassword, documento, correo);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.SendEmailResponse> EnvioCorreoAsync(string tokenEmpresa, string tokenPassword, string documento, string correo) {
            return base.Channel.EnvioCorreoAsync(tokenEmpresa, tokenPassword, documento, correo);
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.DownloadPDFResponse DescargaPDF(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.DescargaPDF(tokenEmpresa, tokenPassword, documento);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DownloadPDFResponse> DescargaPDFAsync(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.DescargaPDFAsync(tokenEmpresa, tokenPassword, documento);
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.DownloadXMLResponse DescargaXML(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.DescargaXML(tokenEmpresa, tokenPassword, documento);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.DownloadXMLResponse> DescargaXMLAsync(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.DescargaXMLAsync(tokenEmpresa, tokenPassword, documento);
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.FoliosRemainingResponse FoliosRestantes(string tokenEmpresa, string tokenPassword) {
            return base.Channel.FoliosRestantes(tokenEmpresa, tokenPassword);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.FoliosRemainingResponse> FoliosRestantesAsync(string tokenEmpresa, string tokenPassword) {
            return base.Channel.FoliosRestantesAsync(tokenEmpresa, tokenPassword);
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.LoadCertificateResponse CargarCertificado(string tokenEmpresa, string tokenPassword, string certificado, string password) {
            return base.Channel.CargarCertificado(tokenEmpresa, tokenPassword, certificado, password);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.LoadCertificateResponse> CargarCertificadoAsync(string tokenEmpresa, string tokenPassword, string certificado, string password) {
            return base.Channel.CargarCertificadoAsync(tokenEmpresa, tokenPassword, certificado, password);
        }
        
        public TrnFacturaElectronica.wsdl_dfacture.ValidateXML ValidarXml(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.ValidarXml(tokenEmpresa, tokenPassword, documento);
        }
        
        public System.Threading.Tasks.Task<TrnFacturaElectronica.wsdl_dfacture.ValidateXML> ValidarXmlAsync(string tokenEmpresa, string tokenPassword, string documento) {
            return base.Channel.ValidarXmlAsync(tokenEmpresa, tokenPassword, documento);
        }
    }
}
